### ISSUE TITLE
Populating calendar visualization from calendar database

### ISSUE THREAD

**Issue by nick11roberts** [ucsdCSE110wi16/CSE110W260T13#18]
Is there anything I should know about for querying the database for the number of events per day in a given month? Perhaps such as doing it asynchronously? I noticed that some of the database stuff was implemented asynchronously and I was unsure if I needed to do that as well. 

This question is directed at @Jen030

**Comment by nick11roberts** [comment]
If I don't need to do this asynchronously, I've isolated the remaining changes that I need to make to a single method, CalendarFragment.getItemsPerDayFromMonth().

**Comment by Jen030** [comment]
If possible, I'd try to do this specific one asynchronously because the
calendar already lags when it is swiped left/right on the months.

If not possible, I mean I think it'll work fine.
