### ISSUE TITLE
CalendarEvent buttons should somehow call UpdateCalendarColors in CalendarFragment

### ISSUE THREAD

**Issue by nick11roberts** [ucsdCSE110wi16/CSE110W260T13#20]
In fact, just the delete button in the adapters doesn't work.

**Comment by Jen030** [comment]
I implemented a callback to updateCalendarColors.

I'm having issues creating a callback to create a dialog in CalendarFragment and then having the dialog return the click value via a callback to the calendarfragment then to the adapter so .... we're just going to have to deal with crappy code.
